# Form implementation generated from reading ui file 'acc_new_or_old.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogOrRegWindow(object):
    def setupUi(self, LogOrRegWindow):
        LogOrRegWindow.setObjectName("LogOrRegWindow")
        LogOrRegWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(LogOrRegWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1921, 1031))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.log_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.log_btn.setMinimumSize(QtCore.QSize(500, 100))
        self.log_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.log_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 36pt \"Helvetica\";\n"
"background-color: rgb(226, 118, 43);")
        self.log_btn.setObjectName("log_btn")
        self.gridLayout.addWidget(self.log_btn, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.reg_syst_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.reg_syst_btn.setMinimumSize(QtCore.QSize(500, 100))
        self.reg_syst_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reg_syst_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 36pt \"Helvetica\";\n"
"background-color: rgb(226, 118, 43);")
        self.reg_syst_btn.setObjectName("reg_syst_btn")
        self.gridLayout.addWidget(self.reg_syst_btn, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.go_back = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.go_back.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_back.sizePolicy().hasHeightForWidth())
        self.go_back.setSizePolicy(sizePolicy)
        self.go_back.setMinimumSize(QtCore.QSize(0, 60))
        self.go_back.setMaximumSize(QtCore.QSize(200, 16777215))
        self.go_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.go_back.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.go_back.setStyleSheet("font: 75 36pt \"Courier\";\n"
"color: rgb(252, 1, 7);\n"
"background-color: rgb(254, 204, 102);\n"
"")
        self.go_back.setObjectName("go_back")
        self.gridLayout.addWidget(self.go_back, 4, 2, 1, 1)
        LogOrRegWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LogOrRegWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 24))
        self.menubar.setObjectName("menubar")
        LogOrRegWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LogOrRegWindow)
        self.statusbar.setObjectName("statusbar")
        LogOrRegWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LogOrRegWindow)
        QtCore.QMetaObject.connectSlotsByName(LogOrRegWindow)

    def retranslateUi(self, LogOrRegWindow):
        _translate = QtCore.QCoreApplication.translate
        LogOrRegWindow.setWindowTitle(_translate("LogOrRegWindow", "Регистрация"))
        self.log_btn.setText(_translate("LogOrRegWindow", "ВОЙТИ"))
        self.reg_syst_btn.setText(_translate("LogOrRegWindow", "ЗАРЕГИСТРИРОВАТЬСЯ"))
        self.go_back.setText(_translate("LogOrRegWindow", "Назад"))
