# Form implementation generated from reading ui file 'crash.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CrashKazWindow(object):
    def setupUi(self, CrashKazWindow):
        CrashKazWindow.setObjectName("CrashKazWindow")
        CrashKazWindow.resize(1920, 1100)
        self.centralwidget = QtWidgets.QWidget(CrashKazWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.go_back = QtWidgets.QPushButton(self.centralwidget)
        self.go_back.setEnabled(True)
        self.go_back.setGeometry(QtCore.QRect(1320, 860, 200, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go_back.sizePolicy().hasHeightForWidth())
        self.go_back.setSizePolicy(sizePolicy)
        self.go_back.setMinimumSize(QtCore.QSize(0, 60))
        self.go_back.setMaximumSize(QtCore.QSize(200, 16777215))
        self.go_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.go_back.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.go_back.setStyleSheet("font: 75 30pt \"Courier\";\n"
"color: rgb(252, 1, 7);\n"
"background-color: rgb(254, 204, 102);\n"
"")
        self.go_back.setObjectName("go_back")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(630, 200, 671, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.coef_txt = QtWidgets.QLabel(self.gridLayoutWidget)
        self.coef_txt.setStyleSheet("font: 20pt \"Courier\";\n"
"color: rgb(0, 0, 0);")
        self.coef_txt.setObjectName("coef_txt")
        self.gridLayout.addWidget(self.coef_txt, 0, 4, 1, 1)
        self.curr_txt = QtWidgets.QLabel(self.gridLayoutWidget)
        self.curr_txt.setStyleSheet("font: 20pt \"Courier\";\n"
"color: rgb(0, 0, 0);")
        self.curr_txt.setObjectName("curr_txt")
        self.gridLayout.addWidget(self.curr_txt, 2, 4, 1, 1)
        self.win_txt = QtWidgets.QLabel(self.gridLayoutWidget)
        self.win_txt.setStyleSheet("font: 20pt \"Courier\";\n"
"color: rgb(0, 0, 0);")
        self.win_txt.setObjectName("win_txt")
        self.gridLayout.addWidget(self.win_txt, 1, 4, 1, 1)
        self.task_txt_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.task_txt_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.task_txt_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 20pt \"Tahoma\";")
        self.task_txt_3.setObjectName("task_txt_3")
        self.gridLayout.addWidget(self.task_txt_3, 1, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("font: 20pt \"Tahoma\";\n"
"color: rgb(128, 0, 2);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.run_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.run_btn.setMinimumSize(QtCore.QSize(300, 70))
        self.run_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.run_btn.setStyleSheet("font: 75 20pt \"Helvetica\";\n"
"background-color: rgb(253, 128, 8);\n"
"color: rgb(255, 255, 255);")
        self.run_btn.setObjectName("run_btn")
        self.gridLayout.addWidget(self.run_btn, 3, 4, 1, 1)
        self.task_txt = QtWidgets.QLabel(self.gridLayoutWidget)
        self.task_txt.setMaximumSize(QtCore.QSize(16777215, 50))
        self.task_txt.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 20pt \"Tahoma\";")
        self.task_txt.setObjectName("task_txt")
        self.gridLayout.addWidget(self.task_txt, 0, 0, 1, 4)
        self.task_txt_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.task_txt_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.task_txt_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 20pt \"Tahoma\";")
        self.task_txt_4.setObjectName("task_txt_4")
        self.gridLayout.addWidget(self.task_txt_4, 2, 0, 1, 4)
        self.stavka_summ = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.stavka_summ.setMinimumSize(QtCore.QSize(200, 50))
        self.stavka_summ.setStyleSheet("font: 20pt \"Courier\";")
        self.stavka_summ.setObjectName("stavka_summ")
        self.gridLayout.addWidget(self.stavka_summ, 3, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1360, 10, 311, 31))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 20pt \"Tahoma\";")
        self.label.setObjectName("label")
        self.curr_hard = QtWidgets.QLabel(self.centralwidget)
        self.curr_hard.setGeometry(QtCore.QRect(1670, 0, 221, 50))
        self.curr_hard.setStyleSheet("font: 20pt \"Courier\";\n"
"color: rgb(128, 0, 2);")
        self.curr_hard.setObjectName("curr_hard")
        self.end_btn = QtWidgets.QPushButton(self.centralwidget)
        self.end_btn.setGeometry(QtCore.QRect(790, 870, 300, 70))
        self.end_btn.setMinimumSize(QtCore.QSize(300, 70))
        self.end_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.end_btn.setStyleSheet("font: 75 20pt \"Helvetica\";\n"
"background-color: rgb(253, 128, 8);\n"
"color: rgb(255, 255, 255);")
        self.end_btn.setObjectName("end_btn")
        CrashKazWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CrashKazWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 24))
        self.menubar.setObjectName("menubar")
        CrashKazWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CrashKazWindow)
        self.statusbar.setObjectName("statusbar")
        CrashKazWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CrashKazWindow)
        QtCore.QMetaObject.connectSlotsByName(CrashKazWindow)

    def retranslateUi(self, CrashKazWindow):
        _translate = QtCore.QCoreApplication.translate
        CrashKazWindow.setWindowTitle(_translate("CrashKazWindow", "Краш-казино"))
        self.go_back.setText(_translate("CrashKazWindow", "Назад"))
        self.coef_txt.setText(_translate("CrashKazWindow", "x0.12"))
        self.curr_txt.setText(_translate("CrashKazWindow", "999"))
        self.win_txt.setText(_translate("CrashKazWindow", "99"))
        self.task_txt_3.setText(_translate("CrashKazWindow", "Сумма выигрыша:"))
        self.label_2.setText(_translate("CrashKazWindow", "Ваша ставка:"))
        self.run_btn.setText(_translate("CrashKazWindow", "КРАШ (дальше)"))
        self.task_txt.setText(_translate("CrashKazWindow", "Коэффициент:"))
        self.task_txt_4.setText(_translate("CrashKazWindow", "Текущий баланс:"))
        self.stavka_summ.setText(_translate("CrashKazWindow", "99999999999999"))
        self.label.setText(_translate("CrashKazWindow", "Текущая сложность:"))
        self.curr_hard.setText(_translate("CrashKazWindow", "None"))
        self.end_btn.setText(_translate("CrashKazWindow", "ЗАКОНЧИТЬ"))
