# Form implementation generated from reading ui file 'invent.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InventWindow(object):
    def setupUi(self, InventWindow):
        InventWindow.setObjectName("InventWindow")
        InventWindow.resize(1920, 1100)
        self.centralwidget = QtWidgets.QWidget(InventWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(350, 170, 1231, 671))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("font: 30pt bold \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 2)
        self.tableInventory = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableInventory.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(253, 138, 8, 191);\n"
"font: 24pt \"Georgia\";")
        self.tableInventory.setObjectName("tableInventory")
        self.tableInventory.setColumnCount(0)
        self.tableInventory.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableInventory, 2, 0, 1, 2)
        self.close_window = QtWidgets.QPushButton(self.centralwidget)
        self.close_window.setGeometry(QtCore.QRect(770, 860, 400, 60))
        self.close_window.setMinimumSize(QtCore.QSize(400, 60))
        self.close_window.setMaximumSize(QtCore.QSize(1000000, 16777215))
        self.close_window.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.close_window.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.close_window.setStyleSheet("font: 75 30pt \"Courier\";\n"
"color: rgb(252, 1, 7);\n"
"background-color: rgb(254, 204, 102);")
        self.close_window.setObjectName("close_window")
        InventWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InventWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 24))
        self.menubar.setObjectName("menubar")
        InventWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InventWindow)
        self.statusbar.setObjectName("statusbar")
        InventWindow.setStatusBar(self.statusbar)

        self.retranslateUi(InventWindow)
        QtCore.QMetaObject.connectSlotsByName(InventWindow)

    def retranslateUi(self, InventWindow):
        _translate = QtCore.QCoreApplication.translate
        InventWindow.setWindowTitle(_translate("InventWindow", "Ваш инвентарь"))
        self.label_3.setText(_translate("InventWindow", "ВАШ ИНВЕНТАРЬ"))
        self.close_window.setText(_translate("InventWindow", "Закрыть окно"))
