# Form implementation generated from reading ui file 'log_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogWindow(object):
    def setupUi(self, LogWindow):
        LogWindow.setObjectName("LogWindow")
        LogWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(LogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(320, 230, 1241, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(450, 0))
        self.label.setStyleSheet("font: 30pt bold \"Helvetica\";\n"
"color: rgb(128, 0, 2);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.username_enter = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.username_enter.setMinimumSize(QtCore.QSize(0, 40))
        self.username_enter.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 20pt \"Courier\";")
        self.username_enter.setObjectName("username_enter")
        self.gridLayout.addWidget(self.username_enter, 0, 1, 1, 1)
        self.psw_enter = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.psw_enter.setMinimumSize(QtCore.QSize(0, 40))
        self.psw_enter.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 20pt \"Courier\";")
        self.psw_enter.setObjectName("psw_enter")
        self.gridLayout.addWidget(self.psw_enter, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("font: 30pt bold \"Helvetica\";\n"
"color: rgb(128, 0, 2);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.log_btn = QtWidgets.QPushButton(self.centralwidget)
        self.log_btn.setGeometry(QtCore.QRect(1040, 580, 500, 100))
        self.log_btn.setMinimumSize(QtCore.QSize(500, 100))
        self.log_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.log_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 30pt \"Helvetica\";\n"
"background-color: rgb(226, 118, 43);")
        self.log_btn.setObjectName("log_btn")
        self.go_back = QtWidgets.QPushButton(self.centralwidget)
        self.go_back.setGeometry(QtCore.QRect(1340, 740, 200, 60))
        self.go_back.setMinimumSize(QtCore.QSize(200, 60))
        self.go_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.go_back.setStyleSheet("font: 75 30pt \"Courier\";\n"
"color: rgb(252, 1, 7);\n"
"background-color: rgb(254, 204, 102);")
        self.go_back.setObjectName("go_back")
        LogWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LogWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 24))
        self.menubar.setObjectName("menubar")
        LogWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LogWindow)
        self.statusbar.setObjectName("statusbar")
        LogWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LogWindow)
        QtCore.QMetaObject.connectSlotsByName(LogWindow)

    def retranslateUi(self, LogWindow):
        _translate = QtCore.QCoreApplication.translate
        LogWindow.setWindowTitle(_translate("LogWindow", "Регистрация"))
        self.label.setText(_translate("LogWindow", "Введите юзернейм"))
        self.label_3.setText(_translate("LogWindow", "Введите пароль"))
        self.log_btn.setText(_translate("LogWindow", "ВОЙТИ"))
        self.go_back.setText(_translate("LogWindow", "Назад"))
