# Form implementation generated from reading ui file 'shop.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ShopWindow(object):
    def setupUi(self, ShopWindow):
        ShopWindow.setObjectName("ShopWindow")
        ShopWindow.resize(1920, 1100)
        ShopWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(ShopWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(360, 190, 1201, 671))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet("font: 36pt bold \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.buy_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buy_btn.setMinimumSize(QtCore.QSize(300, 80))
        self.buy_btn.setMaximumSize(QtCore.QSize(500, 16777215))
        self.buy_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buy_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.buy_btn.setStyleSheet("font: 36pt \"Helvetica\";\n"
"background-color: rgb(253, 119, 15);\n"
"color: rgb(0, 0, 0);")
        self.buy_btn.setObjectName("buy_btn")
        self.gridLayout.addWidget(self.buy_btn, 4, 1, 1, 1)
        self.tableItems = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableItems.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgba(253, 138, 8, 191);\n"
"font: 24pt \"Georgia\";")
        self.tableItems.setObjectName("tableItems")
        self.tableItems.setColumnCount(0)
        self.tableItems.setRowCount(0)
        self.gridLayout.addWidget(self.tableItems, 3, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(1000000, 16777215))
        self.label_2.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 3)
        self.go_back = QtWidgets.QPushButton(self.centralwidget)
        self.go_back.setGeometry(QtCore.QRect(960, 950, 200, 60))
        self.go_back.setMinimumSize(QtCore.QSize(0, 60))
        self.go_back.setMaximumSize(QtCore.QSize(200, 16777215))
        self.go_back.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.go_back.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.go_back.setStyleSheet("font: 75 36pt \"Courier\";\n"
"color: rgb(252, 1, 7);\n"
"background-color: rgb(254, 204, 102);")
        self.go_back.setObjectName("go_back")
        ShopWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ShopWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 24))
        self.menubar.setObjectName("menubar")
        ShopWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ShopWindow)
        self.statusbar.setObjectName("statusbar")
        ShopWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ShopWindow)
        QtCore.QMetaObject.connectSlotsByName(ShopWindow)

    def retranslateUi(self, ShopWindow):
        _translate = QtCore.QCoreApplication.translate
        ShopWindow.setWindowTitle(_translate("ShopWindow", "Магазин"))
        self.label.setText(_translate("ShopWindow", "ТОВАРЫ"))
        self.buy_btn.setText(_translate("ShopWindow", "КУПИТЬ"))
        self.label_2.setText(_translate("ShopWindow", "Щелкните по id товара, который вы хотели бы купить, и нажмите на кнопку\n"
"\"Купить\". После успешной оплаты товар занесется к вам в инвентарь!"))
        self.go_back.setText(_translate("ShopWindow", "Назад"))
